name = "Peg SMP"
author = "Hamish555"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbb6a940ae5e0e3d1fdcf29e36869e477a474dad764041ca03ed588897eaf3c4"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1"]
