name = "Peg SMP"
author = "Hamish555"
version = "1.2.1"
pack-format = "packwiz:1.2.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "735babc41557c6df33935f91fcea832373ff85055722b03a209b83aeb93e1997"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
