name = "Peg SMP"
author = "Hamish555"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14b55b215ef964668ab77570c3d0938b7918f4f76f42b33266bbf52ebdfa52be"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
